apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vulnerabilities.aquasecurity.github.io
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    singular: vulnerability
    plural: vulnerabilities
    kind: Vulnerability
    listKind: VulnerabilityList
    categories:
      - all
    shortNames:
      - vuln
      - vulns
  validation:
    openAPIV3Schema:
      type: object
      required:
        - apiVersion
        - kind
        - metadata
        - report
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        report:
          type: object
          required:
            - scanner
            - artifact
            - summary
            - vulnerabilities
          properties:
            scanner:
              type: object
              required:
                - name
                - vendor
                - version
              properties:
                name:
                  type: string
                vendor:
                  type: string
                version:
                  type: string
            registry:
              type: object
              properties:
                url:
                  type: string
                  format: url
            artifact:
              type: object
              properties:
                repository:
                  type: string
                digest:
                  type: string
                tag:
                  type: string
                mimeType:
                  type: string
            summary:
              type: object
              required:
                - criticalCount
                - highCount
                - mediumCount
                - lowCount
                - unknownCount
              properties:
                criticalCount:
                  type: integer
                  minimum: 0
                highCount:
                  type: integer
                  minimum: 0
                mediumCount:
                  type: integer
                  minimum: 0
                lowCount:
                  type: integer
                  minimum: 0
                unknownCount:
                  type: integer
                  minimum: 0
            vulnerabilities:
              type: array
              items:
                type: object
                required:
                  - vulnerabilityID
                  - resource
                  - installedVersion
                  - fixedVersion
                  - severity
                  - title
                properties:
                  vulnerabilityID:
                    type: string
                  resource:
                    type: string
                  installedVersion:
                    type: string
                  fixedVersion:
                    type: string
                  severity:
                    type: string
                    enum:
                      - CRITICAL
                      - HIGH
                      - MEDIUM
                      - LOW
                      - UNKNOWN
                  title:
                    type: string
                  description:
                    type: string
                  layerID:
                    type: string
                  links:
                    type: array
                    items:
                      type: string
