FROM alpine:3.9

RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

RUN apk update \
    && apk upgrade musl \
    && apk add ca-certificates dpkg@edge rpm@edge expat@edge libbz2@edge libarchive@edge db@edge

# RUN adduser -u 10000 -D -g '' starboard starboard

COPY scanner-aqua /usr/local/bin/scanner-aqua

# USER starboard

ENTRYPOINT ["scanner-aqua"]
