// Code generated by qtc from "basicpage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line pkg/report/templates/basicpage.qtpl:3
package templates

//line pkg/report/templates/basicpage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/report/templates/basicpage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/report/templates/basicpage.qtpl:4
type Page interface {
//line pkg/report/templates/basicpage.qtpl:4
	Title() string
//line pkg/report/templates/basicpage.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line pkg/report/templates/basicpage.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line pkg/report/templates/basicpage.qtpl:4
	Body() string
//line pkg/report/templates/basicpage.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line pkg/report/templates/basicpage.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line pkg/report/templates/basicpage.qtpl:4
}

// Page prints a page implementing Page interface.

//line pkg/report/templates/basicpage.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line pkg/report/templates/basicpage.qtpl:12
	qw422016.N().S(`
<html>
	<head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
		<title>`)
//line pkg/report/templates/basicpage.qtpl:16
	p.StreamTitle(qw422016)
//line pkg/report/templates/basicpage.qtpl:16
	qw422016.N().S(`</title>
	</head>
	<body>
		<div>
			<a href="/">return to main page</a>
		</div>
		`)
//line pkg/report/templates/basicpage.qtpl:22
	p.StreamBody(qw422016)
//line pkg/report/templates/basicpage.qtpl:22
	qw422016.N().S(`
	</body>
</html>
`)
//line pkg/report/templates/basicpage.qtpl:25
}

//line pkg/report/templates/basicpage.qtpl:25
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line pkg/report/templates/basicpage.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/basicpage.qtpl:25
	StreamPageTemplate(qw422016, p)
//line pkg/report/templates/basicpage.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/basicpage.qtpl:25
}

//line pkg/report/templates/basicpage.qtpl:25
func PageTemplate(p Page) string {
//line pkg/report/templates/basicpage.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/basicpage.qtpl:25
	WritePageTemplate(qb422016, p)
//line pkg/report/templates/basicpage.qtpl:25
	qs422016 := string(qb422016.B)
//line pkg/report/templates/basicpage.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/basicpage.qtpl:25
	return qs422016
//line pkg/report/templates/basicpage.qtpl:25
}
