// Code generated by qtc from "default.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/report/templates/default.qtpl:1
package templates

//line pkg/report/templates/default.qtpl:1
import "github.com/aquasecurity/starboard/pkg/apis/aquasecurity/v1alpha1"

//line pkg/report/templates/default.qtpl:2
import "github.com/aquasecurity/starboard/pkg/kube"

//line pkg/report/templates/default.qtpl:3
import "github.com/aquasecurity/starboard/pkg/find/vulnerabilities"

//line pkg/report/templates/default.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/report/templates/default.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/report/templates/default.qtpl:7
type ReportPage struct {
	VulnsReports      vulnerabilities.WorkloadVulnerabilities
	ConfigAuditReport v1alpha1.ConfigAuditReport
	Workload          kube.Object
}

type ConfigAuditSummary struct {
	PodPass       int
	PodFail       int
	ContainerPass int
	ContainerFail int
}

//line pkg/report/templates/default.qtpl:21
func (p *ReportPage) StreamTitle(qw422016 *qt422016.Writer) {
//line pkg/report/templates/default.qtpl:21
	qw422016.N().S(`
	Starboard Security Report - `)
//line pkg/report/templates/default.qtpl:22
	qw422016.E().S(p.Workload.Namespace)
//line pkg/report/templates/default.qtpl:22
	qw422016.N().S(`/`)
//line pkg/report/templates/default.qtpl:22
	qw422016.E().S(string(p.Workload.Kind))
//line pkg/report/templates/default.qtpl:22
	qw422016.N().S(`/`)
//line pkg/report/templates/default.qtpl:22
	qw422016.E().S(p.Workload.Name)
//line pkg/report/templates/default.qtpl:22
	qw422016.N().S(`
`)
//line pkg/report/templates/default.qtpl:23
}

//line pkg/report/templates/default.qtpl:23
func (p *ReportPage) WriteTitle(qq422016 qtio422016.Writer) {
//line pkg/report/templates/default.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/default.qtpl:23
	p.StreamTitle(qw422016)
//line pkg/report/templates/default.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/default.qtpl:23
}

//line pkg/report/templates/default.qtpl:23
func (p *ReportPage) Title() string {
//line pkg/report/templates/default.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/default.qtpl:23
	p.WriteTitle(qb422016)
//line pkg/report/templates/default.qtpl:23
	qs422016 := string(qb422016.B)
//line pkg/report/templates/default.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/default.qtpl:23
	return qs422016
//line pkg/report/templates/default.qtpl:23
}

//line pkg/report/templates/default.qtpl:27
func (p *ReportPage) GetMergedVulnsSummary() v1alpha1.VulnerabilitySummary {
	merged := v1alpha1.VulnerabilitySummary{}
	for _, report := range p.VulnsReports {
		merged.CriticalCount += report.Summary.CriticalCount
		merged.HighCount += report.Summary.HighCount
		merged.MediumCount += report.Summary.MediumCount
		merged.LowCount += report.Summary.LowCount
		merged.UnknownCount += report.Summary.UnknownCount
	}
	return merged
}

//line pkg/report/templates/default.qtpl:41
func (p *ReportPage) GetConfigAuditSummary() ConfigAuditSummary {
	summary := ConfigAuditSummary{}
	// sum container checks
	for _, checks := range p.ConfigAuditReport.Report.ContainerChecks {
		for _, check := range checks {
			if check.Success {
				summary.ContainerPass += 1
			} else {
				summary.ContainerFail += 1
			}
		}
	}
	// sum pod checks
	for _, check := range p.ConfigAuditReport.Report.PodChecks {
		if check.Success {
			summary.PodPass += 1
		} else {
			summary.PodFail += 1
		}
	}

	return summary
}

//line pkg/report/templates/default.qtpl:67
func (p *ReportPage) StreamBody(qw422016 *qt422016.Writer) {
//line pkg/report/templates/default.qtpl:67
	qw422016.N().S(`
	<style>
  a {
    color: inherit;
  }
  </style>
  <div class="container border-right border-left" style="height: 100%; overflow: scroll;">
            <div class="col mt-5">
                <div class="row text-center">
                    <img style="width: 25vh" class="mx-auto" src="https://www.aquasec.com/wp-content/uploads/2016/05/aqua_logo_fullcolor.png" alt="">
                </div>
                <div class="row mt-4 text-center">
                    <h2 class="text-muted mx-auto">Starboard Security Report for<br>
                </div>
                <div class="row text-center">
                    <h2 class="text-muted mx-auto">`)
//line pkg/report/templates/default.qtpl:82
	qw422016.E().S(string(p.Workload.Kind))
//line pkg/report/templates/default.qtpl:82
	qw422016.N().S(` `)
//line pkg/report/templates/default.qtpl:82
	qw422016.E().S(p.Workload.Name)
//line pkg/report/templates/default.qtpl:82
	qw422016.N().S(` in namespace `)
//line pkg/report/templates/default.qtpl:82
	qw422016.E().S(p.Workload.Namespace)
//line pkg/report/templates/default.qtpl:82
	qw422016.N().S(`</h2>
                </div>

		  
                <div class="row mt-5 px-3">
                    <h4>Table Of Contents</h4>
                </div>
                <div class="row">
                    <ul>
                        `)
//line pkg/report/templates/default.qtpl:91
	if len(p.VulnsReports) > 0 {
//line pkg/report/templates/default.qtpl:91
		qw422016.N().S(`
                        <li>
                            <a href="#vuln_header">Vulnerabilities</a></li>
                            <ul>
                              `)
//line pkg/report/templates/default.qtpl:95
		for container, _ := range p.VulnsReports {
//line pkg/report/templates/default.qtpl:95
			qw422016.N().S(`
                                <li><a href="#vulns_container_`)
//line pkg/report/templates/default.qtpl:96
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:96
			qw422016.N().S(`">`)
//line pkg/report/templates/default.qtpl:96
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:96
			qw422016.N().S(`</a></li>
                              `)
//line pkg/report/templates/default.qtpl:97
		}
//line pkg/report/templates/default.qtpl:97
		qw422016.N().S(`
                            </ul>
                        </li>
                        `)
//line pkg/report/templates/default.qtpl:100
	}
//line pkg/report/templates/default.qtpl:100
	qw422016.N().S(`
                        `)
//line pkg/report/templates/default.qtpl:101
	if len(p.ConfigAuditReport.Report.PodChecks) > 0 {
//line pkg/report/templates/default.qtpl:101
		qw422016.N().S(`
                        <li>
                            <a href="#ca_header">Configuration Audit</a>
                            <ul>
                              <li><a href="#ca_pod_checks">Pod Checks</a></li>
                                `)
//line pkg/report/templates/default.qtpl:106
		for container, _ := range p.ConfigAuditReport.Report.ContainerChecks {
//line pkg/report/templates/default.qtpl:106
			qw422016.N().S(`
                                  <li><a href="#ca_container_`)
//line pkg/report/templates/default.qtpl:107
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:107
			qw422016.N().S(`">`)
//line pkg/report/templates/default.qtpl:107
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:107
			qw422016.N().S(`</a></li>
                                `)
//line pkg/report/templates/default.qtpl:108
		}
//line pkg/report/templates/default.qtpl:108
		qw422016.N().S(`
                            </ul>
                        </li>
                        `)
//line pkg/report/templates/default.qtpl:111
	}
//line pkg/report/templates/default.qtpl:111
	qw422016.N().S(`
                    </ul>
                </div>


                `)
//line pkg/report/templates/default.qtpl:116
	if len(p.VulnsReports) > 0 {
//line pkg/report/templates/default.qtpl:116
		qw422016.N().S(`
                <!-- Vulnerabilities -->
                <div class="row text-center border-bottom mt-4">
                    <h3 class="mx-auto " id="vuln_header" style="color: rgb(0, 160, 170);">Vulnerabilities</h3>
                </div>
                <!-- Cards -->
                <div class="">
                    <div class="row my-5" style="font-size:small;">
                        <!-- Scanner -->
                        <div class="col-3 border rounded shadow px-3 py-2 ml-4 ">
                            <div class="row text-center">
                                <div class="col">
                                    <p class="mb-2 pb-1 border-bottom">Scanner</p>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col">
                                `)
//line pkg/report/templates/default.qtpl:134
		var scanner_name, scanner_vendor, scanner_version, creation_timestamp string
		for _, report := range p.VulnsReports {
			scanner_name = report.Scanner.Name
			scanner_vendor = report.Scanner.Vendor
			scanner_version = report.Scanner.Version
			// TODO: get the timestamp when it is intergrated
			creation_timestamp = ""
			break
		}

//line pkg/report/templates/default.qtpl:143
		qw422016.N().S(`
                                    <p class="my-0">Name:  `)
//line pkg/report/templates/default.qtpl:144
		qw422016.E().S(scanner_name)
//line pkg/report/templates/default.qtpl:144
		qw422016.N().S(`</p>
                                    <p class="my-0">Vendor:  `)
//line pkg/report/templates/default.qtpl:145
		qw422016.E().S(scanner_vendor)
//line pkg/report/templates/default.qtpl:145
		qw422016.N().S(`</p>
                                    <p class="my-0">Version:  `)
//line pkg/report/templates/default.qtpl:146
		qw422016.E().S(scanner_version)
//line pkg/report/templates/default.qtpl:146
		qw422016.N().S(`</p>
                                </div>
                             </div>
                        </div>
                        <!-- summary -->
                        <div class="col-5 border rounded shadow py-2 mx-auto ">
                            <div class="row text-center">
                               <div class="col">
                                   <p class="mb-2 pb-1 border-bottom">Summary</p>
                               </div>
                            </div>
                            <div class="row">
                                `)
//line pkg/report/templates/default.qtpl:159
		summary := p.GetMergedVulnsSummary()

//line pkg/report/templates/default.qtpl:160
		qw422016.N().S(`
                                `)
//line pkg/report/templates/default.qtpl:161
		if summary.CriticalCount > 0 {
//line pkg/report/templates/default.qtpl:161
			qw422016.N().S(`
                                <div class="col text-center p-0 text-danger font-weight-bold">
                                `)
//line pkg/report/templates/default.qtpl:163
		} else {
//line pkg/report/templates/default.qtpl:163
			qw422016.N().S(`
                                <div class="col text-center p-0">
                                `)
//line pkg/report/templates/default.qtpl:165
		}
//line pkg/report/templates/default.qtpl:165
		qw422016.N().S(`
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:166
		qw422016.N().D(summary.CriticalCount)
//line pkg/report/templates/default.qtpl:166
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">CRITICAL</p>
                                </div>
                                `)
//line pkg/report/templates/default.qtpl:169
		if summary.HighCount > 0 {
//line pkg/report/templates/default.qtpl:169
			qw422016.N().S(`
                                <div class="col text-center p-0 text-danger font-weight-bold">
                                `)
//line pkg/report/templates/default.qtpl:171
		} else {
//line pkg/report/templates/default.qtpl:171
			qw422016.N().S(`
                                <div class="col text-center p-0">
                                `)
//line pkg/report/templates/default.qtpl:173
		}
//line pkg/report/templates/default.qtpl:173
		qw422016.N().S(`
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:174
		qw422016.N().D(summary.HighCount)
//line pkg/report/templates/default.qtpl:174
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">HIGH</p>
                                </div>
                                `)
//line pkg/report/templates/default.qtpl:177
		if summary.MediumCount > 0 {
//line pkg/report/templates/default.qtpl:177
			qw422016.N().S(`
                                <div class="col text-center p-0 text-warning font-weight-bold">
                                `)
//line pkg/report/templates/default.qtpl:179
		} else {
//line pkg/report/templates/default.qtpl:179
			qw422016.N().S(`
                                <div class="col text-center p-0">
                                `)
//line pkg/report/templates/default.qtpl:181
		}
//line pkg/report/templates/default.qtpl:181
		qw422016.N().S(`
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:182
		qw422016.N().D(summary.MediumCount)
//line pkg/report/templates/default.qtpl:182
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">MEDIUM</p>
                                </div>
                                <div class="col text-center p-0">
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:186
		qw422016.N().D(summary.LowCount)
//line pkg/report/templates/default.qtpl:186
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">LOW</p>
                                </div>
                                <div class="col text-center p-0">
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:190
		qw422016.N().D(summary.UnknownCount)
//line pkg/report/templates/default.qtpl:190
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">UNKNOWN</p>
                                </div>
                            </div>
                        </div>
                        <!-- Metadata -->
                        <div class="col-3 border rounded shadow px-3 py-2 mr-4">
                            <div class="row text-center">
                                <div class="col">
                                    <p class="mb-2 pb-1 border-bottom">Metadata</p>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col">
                                    <p class="my-0">Generated at:  `)
//line pkg/report/templates/default.qtpl:204
		qw422016.E().S(creation_timestamp)
//line pkg/report/templates/default.qtpl:204
		qw422016.N().S(`</p>
                                </div>
                             </div>
                        </div>

                    </div>      
                </div>
                `)
//line pkg/report/templates/default.qtpl:211
	}
//line pkg/report/templates/default.qtpl:211
	qw422016.N().S(`
                
                `)
//line pkg/report/templates/default.qtpl:213
	for container, report := range p.VulnsReports {
//line pkg/report/templates/default.qtpl:213
		qw422016.N().S(`
                
                  <div class="row"><h5 class="text-info" id="vulns_container_`)
//line pkg/report/templates/default.qtpl:215
		qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:215
		qw422016.N().S(`">Container `)
//line pkg/report/templates/default.qtpl:215
		qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:215
		qw422016.N().S(`</h5></div>
                  <div class="row"><p>`)
//line pkg/report/templates/default.qtpl:216
		qw422016.E().S(report.Registry.URL)
//line pkg/report/templates/default.qtpl:216
		qw422016.N().S(`/`)
//line pkg/report/templates/default.qtpl:216
		qw422016.E().S(report.Artifact.Repository)
//line pkg/report/templates/default.qtpl:216
		qw422016.N().S(`:`)
//line pkg/report/templates/default.qtpl:216
		qw422016.E().S(report.Artifact.Tag)
//line pkg/report/templates/default.qtpl:216
		qw422016.N().S(`</p></div>
                  `)
//line pkg/report/templates/default.qtpl:217
		if len(report.Vulnerabilities) == 0 {
//line pkg/report/templates/default.qtpl:217
			qw422016.N().S(`
                    <div class="row">
                      <p class="alert alert-success py-0 m-0" style="font-size: small;">No Vulnerabilities</p>
                    </div>                  
                  `)
//line pkg/report/templates/default.qtpl:221
		} else {
//line pkg/report/templates/default.qtpl:221
			qw422016.N().S(`

                  <div class="row">
                      <table class="table table-sm table-bordered">
                          <thead>
                              <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Severity</th>
                                <th scope="col">Resource</th>
                                <th scope="col">Installed Version</th>
                                <th scope="col">Fixed Version</th>
                              </tr>
                            </thead>
                            <tbody>
                  `)
//line pkg/report/templates/default.qtpl:235
			for _, v := range report.Vulnerabilities {
//line pkg/report/templates/default.qtpl:235
				qw422016.N().S(`
                    <tr>
                      <td>`)
//line pkg/report/templates/default.qtpl:237
				qw422016.E().S(v.VulnerabilityID)
//line pkg/report/templates/default.qtpl:237
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:238
				qw422016.E().S(string(v.Severity))
//line pkg/report/templates/default.qtpl:238
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:239
				qw422016.E().S(v.Resource)
//line pkg/report/templates/default.qtpl:239
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:240
				qw422016.E().S(v.InstalledVersion)
//line pkg/report/templates/default.qtpl:240
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:241
				qw422016.E().S(v.FixedVersion)
//line pkg/report/templates/default.qtpl:241
				qw422016.N().S(`</td>
                    </tr>	
                  `)
//line pkg/report/templates/default.qtpl:243
			}
//line pkg/report/templates/default.qtpl:243
			qw422016.N().S(`
                            </tbody>
                      </table>
                  </div>
                `)
//line pkg/report/templates/default.qtpl:247
		}
//line pkg/report/templates/default.qtpl:247
		qw422016.N().S(`
                `)
//line pkg/report/templates/default.qtpl:248
	}
//line pkg/report/templates/default.qtpl:248
	qw422016.N().S(`
                

                <!-- Config Audits -->
                `)
//line pkg/report/templates/default.qtpl:252
	if len(p.ConfigAuditReport.Report.PodChecks) > 0 {
//line pkg/report/templates/default.qtpl:252
		qw422016.N().S(`
                  <div class="row pt-3 text-center border-bottom my-4">
                      <h3 class="mx-auto" id="ca_header" style="color: rgb(0, 160, 170);">Configuration Audit</h3>
                  </div>
                  <!-- Cards -->
                <div class="">
                    <div class="row my-5" style="font-size:small;">
                        <!-- Scanner -->
                        <div class="col-3 border rounded shadow px-3 py-2 ml-4 ">
                            <div class="row text-center">
                                <div class="col">
                                    <p class="mb-2 pb-1 border-bottom">Scanner</p>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col">
                                    <p class="my-0">Name:  `)
//line pkg/report/templates/default.qtpl:268
		qw422016.E().S(p.ConfigAuditReport.Report.Scanner.Name)
//line pkg/report/templates/default.qtpl:268
		qw422016.N().S(`</p>
                                    <p class="my-0">Vendor:  `)
//line pkg/report/templates/default.qtpl:269
		qw422016.E().S(p.ConfigAuditReport.Report.Scanner.Vendor)
//line pkg/report/templates/default.qtpl:269
		qw422016.N().S(`</p>
                                    <p class="my-0">Version:  `)
//line pkg/report/templates/default.qtpl:270
		qw422016.E().S(p.ConfigAuditReport.Report.Scanner.Version)
//line pkg/report/templates/default.qtpl:270
		qw422016.N().S(`</p>
                                </div>
                             </div>
                        </div>
                        <!-- summary -->
                        <div class="col-3 border rounded shadow py-2 mx-auto ">
                            <div class="row text-center">
                               <div class="col">
                                   <p class="mb-2 pb-1 border-bottom">Summary</p>
                               </div>
                            </div>
                            <div class="row">
                                `)
//line pkg/report/templates/default.qtpl:283
		summary := p.GetConfigAuditSummary()
		sumPass := summary.PodPass + summary.ContainerPass
		sumFail := summary.PodFail + summary.ContainerFail

//line pkg/report/templates/default.qtpl:286
		qw422016.N().S(`
                                `)
//line pkg/report/templates/default.qtpl:287
		if sumPass > 0 {
//line pkg/report/templates/default.qtpl:287
			qw422016.N().S(`
                                <div class="col text-center p-0 text-success font-weight-bold">
                                `)
//line pkg/report/templates/default.qtpl:289
		} else {
//line pkg/report/templates/default.qtpl:289
			qw422016.N().S(`
                                <div class="col text-center p-0">
                                `)
//line pkg/report/templates/default.qtpl:291
		}
//line pkg/report/templates/default.qtpl:291
		qw422016.N().S(`
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:292
		qw422016.N().D(sumPass)
//line pkg/report/templates/default.qtpl:292
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">PASS</p>
                                </div>
                                `)
//line pkg/report/templates/default.qtpl:295
		if sumFail > 0 {
//line pkg/report/templates/default.qtpl:295
			qw422016.N().S(`
                                <div class="col text-center p-0 text-danger font-weight-bold">
                                `)
//line pkg/report/templates/default.qtpl:297
		} else {
//line pkg/report/templates/default.qtpl:297
			qw422016.N().S(`
                                <div class="col text-center p-0">
                                `)
//line pkg/report/templates/default.qtpl:299
		}
//line pkg/report/templates/default.qtpl:299
		qw422016.N().S(`
                                    <p class="mx-auto mb-1">`)
//line pkg/report/templates/default.qtpl:300
		qw422016.N().D(sumFail)
//line pkg/report/templates/default.qtpl:300
		qw422016.N().S(`</p>
                                    <p class="mx-auto ">FAIL</p>
                                </div>
                            </div>
                        </div>
                        <!-- Metadata -->
                        <div class="col-3 border rounded shadow px-3 py-2 mr-4">
                            <div class="row text-center">
                                <div class="col">
                                    <p class="mb-2 pb-1 border-bottom">Metadata</p>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col">
                                    <p class="my-0">Generated at:  `)
//line pkg/report/templates/default.qtpl:314
		qw422016.E().S(p.ConfigAuditReport.CreationTimestamp.String())
//line pkg/report/templates/default.qtpl:314
		qw422016.N().S(`</p>
                                </div>
                             </div>
                        </div>

                    </div>      
                </div>
                  <div class="row"><h5 class="text-info" id="ca_pod_checks">Pod Checks</h5></div>
                  <div class="row">
                      <table class="table table-sm table-bordered">
                          <thead>
                              <tr>
                                <th scope="col">Success</th>
                                <th scope="col">ID</th>
                                <th scope="col">Severity</th>
                                <th scope="col">Category</th>
                              </tr>
                            </thead>
                            <tbody>
                              `)
//line pkg/report/templates/default.qtpl:333
		for _, check := range p.ConfigAuditReport.Report.PodChecks {
//line pkg/report/templates/default.qtpl:333
			qw422016.N().S(`
                                <tr>
                                  <td>`)
//line pkg/report/templates/default.qtpl:335
			qw422016.E().V(check.Success)
//line pkg/report/templates/default.qtpl:335
			qw422016.N().S(`</td>
                                  <td>`)
//line pkg/report/templates/default.qtpl:336
			qw422016.E().S(check.ID)
//line pkg/report/templates/default.qtpl:336
			qw422016.N().S(`</td>
                                  <td>`)
//line pkg/report/templates/default.qtpl:337
			qw422016.E().S(check.Severity)
//line pkg/report/templates/default.qtpl:337
			qw422016.N().S(`</td>
                                  <td>`)
//line pkg/report/templates/default.qtpl:338
			qw422016.E().S(check.Category)
//line pkg/report/templates/default.qtpl:338
			qw422016.N().S(`</td>
                                </tr>
                              `)
//line pkg/report/templates/default.qtpl:340
		}
//line pkg/report/templates/default.qtpl:340
		qw422016.N().S(`
                            </tbody>
                      </table>
                  </div>
                  `)
//line pkg/report/templates/default.qtpl:344
		for container, checks := range p.ConfigAuditReport.Report.ContainerChecks {
//line pkg/report/templates/default.qtpl:344
			qw422016.N().S(`
                    <div class="row"><h5 class="text-info" id="ca_container_`)
//line pkg/report/templates/default.qtpl:345
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:345
			qw422016.N().S(`">Container `)
//line pkg/report/templates/default.qtpl:345
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:345
			qw422016.N().S(`</h5></div>
                    <div class="row">
                        <table class="table table-sm table-bordered">
                            <thead>
                                <tr>
                                  <th scope="col">Success</th>
                                  <th scope="col">ID</th>
                                  <th scope="col">Severity</th>
                                  <th scope="col">Category</th>
                                </tr>
                              </thead>
                              <tbody>
                                `)
//line pkg/report/templates/default.qtpl:357
			for _, check := range checks {
//line pkg/report/templates/default.qtpl:357
				qw422016.N().S(`
                                  <tr>
                                    <td>`)
//line pkg/report/templates/default.qtpl:359
				qw422016.E().V(check.Success)
//line pkg/report/templates/default.qtpl:359
				qw422016.N().S(`</td>
                                    <td>`)
//line pkg/report/templates/default.qtpl:360
				qw422016.E().S(check.ID)
//line pkg/report/templates/default.qtpl:360
				qw422016.N().S(`</td>
                                    <td>`)
//line pkg/report/templates/default.qtpl:361
				qw422016.E().S(check.Severity)
//line pkg/report/templates/default.qtpl:361
				qw422016.N().S(`</td>
                                    <td>`)
//line pkg/report/templates/default.qtpl:362
				qw422016.E().S(check.Category)
//line pkg/report/templates/default.qtpl:362
				qw422016.N().S(`</td>
                                  </tr>
                                `)
//line pkg/report/templates/default.qtpl:364
			}
//line pkg/report/templates/default.qtpl:364
			qw422016.N().S(`
                              </tbody>
                        </table>
                    </div>
                  `)
//line pkg/report/templates/default.qtpl:368
		}
//line pkg/report/templates/default.qtpl:368
		qw422016.N().S(`
                  `)
//line pkg/report/templates/default.qtpl:369
	}
//line pkg/report/templates/default.qtpl:369
	qw422016.N().S(`
            </div>
        </div>
`)
//line pkg/report/templates/default.qtpl:372
}

//line pkg/report/templates/default.qtpl:372
func (p *ReportPage) WriteBody(qq422016 qtio422016.Writer) {
//line pkg/report/templates/default.qtpl:372
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/default.qtpl:372
	p.StreamBody(qw422016)
//line pkg/report/templates/default.qtpl:372
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/default.qtpl:372
}

//line pkg/report/templates/default.qtpl:372
func (p *ReportPage) Body() string {
//line pkg/report/templates/default.qtpl:372
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/default.qtpl:372
	p.WriteBody(qb422016)
//line pkg/report/templates/default.qtpl:372
	qs422016 := string(qb422016.B)
//line pkg/report/templates/default.qtpl:372
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/default.qtpl:372
	return qs422016
//line pkg/report/templates/default.qtpl:372
}
