// Code generated by qtc from "default.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/report/templates/default.qtpl:1
package templates

//line pkg/report/templates/default.qtpl:1
import "github.com/aquasecurity/starboard/pkg/apis/aquasecurity/v1alpha1"

//line pkg/report/templates/default.qtpl:2
import "github.com/aquasecurity/starboard/pkg/kube"

//line pkg/report/templates/default.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/report/templates/default.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/report/templates/default.qtpl:6
type ReportPage struct {
	VulnsReports       []v1alpha1.Vulnerability
	ConfigAuditReports []v1alpha1.ConfigAuditReport
	Workload           kube.Object
}

//line pkg/report/templates/default.qtpl:14
func (p *ReportPage) StreamTitle(qw422016 *qt422016.Writer) {
//line pkg/report/templates/default.qtpl:14
	qw422016.N().S(`
	Starboard Security Report - `)
//line pkg/report/templates/default.qtpl:15
	qw422016.E().S(p.Workload.Namespace)
//line pkg/report/templates/default.qtpl:15
	qw422016.N().S(`/`)
//line pkg/report/templates/default.qtpl:15
	qw422016.E().S(string(p.Workload.Kind))
//line pkg/report/templates/default.qtpl:15
	qw422016.N().S(`/`)
//line pkg/report/templates/default.qtpl:15
	qw422016.E().S(p.Workload.Name)
//line pkg/report/templates/default.qtpl:15
	qw422016.N().S(`
`)
//line pkg/report/templates/default.qtpl:16
}

//line pkg/report/templates/default.qtpl:16
func (p *ReportPage) WriteTitle(qq422016 qtio422016.Writer) {
//line pkg/report/templates/default.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/default.qtpl:16
	p.StreamTitle(qw422016)
//line pkg/report/templates/default.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/default.qtpl:16
}

//line pkg/report/templates/default.qtpl:16
func (p *ReportPage) Title() string {
//line pkg/report/templates/default.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/default.qtpl:16
	p.WriteTitle(qb422016)
//line pkg/report/templates/default.qtpl:16
	qs422016 := string(qb422016.B)
//line pkg/report/templates/default.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/default.qtpl:16
	return qs422016
//line pkg/report/templates/default.qtpl:16
}

//line pkg/report/templates/default.qtpl:20
func (p *ReportPage) GetMergedVulnsSummary() v1alpha1.VulnerabilitySummary {
	merged := v1alpha1.VulnerabilitySummary{}
	for _, report := range p.VulnsReports {
		merged.CriticalCount += report.Report.Summary.CriticalCount
		merged.HighCount += report.Report.Summary.HighCount
		merged.MediumCount += report.Report.Summary.MediumCount
		merged.LowCount += report.Report.Summary.LowCount
		merged.UnknownCount += report.Report.Summary.UnknownCount
	}
	return merged
}

//line pkg/report/templates/default.qtpl:35
func (p *ReportPage) StreamBody(qw422016 *qt422016.Writer) {
//line pkg/report/templates/default.qtpl:35
	qw422016.N().S(`
	<style>
  a {
    color: inherit;
  }
  </style>
  <div class="container border-right border-left" style="height: 100%; overflow: scroll;">
            <div class="col mt-5">
                <div class="row text-center">
                    <img style="width: 25vh" class="mx-auto" src="https://www.aquasec.com/wp-content/uploads/2016/05/aqua_logo_fullcolor.png" alt="">
                </div>
                <div class="row mt-4 text-center">
                    <h2 class="text-muted mx-auto">Starboard Security Report for<br>
                </div>
                <div class="row text-center">
                    <h2 class="text-muted mx-auto">`)
//line pkg/report/templates/default.qtpl:50
	qw422016.E().S(string(p.Workload.Kind))
//line pkg/report/templates/default.qtpl:50
	qw422016.N().S(` `)
//line pkg/report/templates/default.qtpl:50
	qw422016.E().S(p.Workload.Name)
//line pkg/report/templates/default.qtpl:50
	qw422016.N().S(` in namespace `)
//line pkg/report/templates/default.qtpl:50
	qw422016.E().S(p.Workload.Namespace)
//line pkg/report/templates/default.qtpl:50
	qw422016.N().S(`</h2>
                </div>

		  
                <div class="row mt-5 px-3">
                    <h4>Table Of Contents</h4>
                </div>
                <div class="row">
                    <ul>
                        `)
//line pkg/report/templates/default.qtpl:59
	if len(p.VulnsReports) > 0 {
//line pkg/report/templates/default.qtpl:59
		qw422016.N().S(`
                        <li>
                            <a href="#vuln_header">Vulnerabilities</a></li>
                            <ul>
                              `)
//line pkg/report/templates/default.qtpl:63
		for count, report := range p.VulnsReports {
//line pkg/report/templates/default.qtpl:63
			qw422016.N().S(`
                                <li><a href="#vulns_container_`)
//line pkg/report/templates/default.qtpl:64
			qw422016.N().D(count)
//line pkg/report/templates/default.qtpl:64
			qw422016.N().S(`">`)
//line pkg/report/templates/default.qtpl:64
			qw422016.E().S(report.Labels["starboard.container.name"])
//line pkg/report/templates/default.qtpl:64
			qw422016.N().S(`</a></li>
                              `)
//line pkg/report/templates/default.qtpl:65
		}
//line pkg/report/templates/default.qtpl:65
		qw422016.N().S(`
                            </ul>
                        </li>
                        `)
//line pkg/report/templates/default.qtpl:68
	}
//line pkg/report/templates/default.qtpl:68
	qw422016.N().S(`
                        `)
//line pkg/report/templates/default.qtpl:69
	if len(p.ConfigAuditReports) > 0 {
//line pkg/report/templates/default.qtpl:69
		qw422016.N().S(`
                        <li>
                            <a href="#ca_header">Configuration Audit</a>
                            <ul>
                              <li><a href="#ca_pod_checks">Pod Checks</a></li>
                              `)
//line pkg/report/templates/default.qtpl:74
		for _, report := range p.ConfigAuditReports {
//line pkg/report/templates/default.qtpl:74
			qw422016.N().S(`
                                `)
//line pkg/report/templates/default.qtpl:75
			for container, _ := range report.Report.ContainerChecks {
//line pkg/report/templates/default.qtpl:75
				qw422016.N().S(`
                                  <li><a href="#ca_container_`)
//line pkg/report/templates/default.qtpl:76
				qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:76
				qw422016.N().S(`">`)
//line pkg/report/templates/default.qtpl:76
				qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:76
				qw422016.N().S(`</a></li>
                                `)
//line pkg/report/templates/default.qtpl:77
			}
//line pkg/report/templates/default.qtpl:77
			qw422016.N().S(`
                              `)
//line pkg/report/templates/default.qtpl:78
		}
//line pkg/report/templates/default.qtpl:78
		qw422016.N().S(`
                            </ul>
                        </li>
                        `)
//line pkg/report/templates/default.qtpl:81
	}
//line pkg/report/templates/default.qtpl:81
	qw422016.N().S(`
                    </ul>
                </div>


                `)
//line pkg/report/templates/default.qtpl:86
	if len(p.VulnsReports) > 0 {
//line pkg/report/templates/default.qtpl:86
		qw422016.N().S(`
                <!-- Vulnerabilities -->
                <div class="row pt-3 text-center border-bottom mt-4">
                    <h3 class="mx-auto " id="vuln_header" style="color: rgb(0, 160, 170);">Vulnerabilities</h3>
                </div>
                <!-- Cards -->
                <div class="">
                    <div class="row my-5" style="font-size:small;">
                        <!-- Scanner -->
                        <div class="col-3 border rounded shadow px-3 py-2 ml-4 ">
                            <div class="row text-center">
                                <div class="col">
                                    <p class="mb-2 pb-1 border-bottom">Scanner</p>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col">
                                    <p class="my-0">Name:  `)
//line pkg/report/templates/default.qtpl:103
		qw422016.E().S(p.VulnsReports[0].Report.Scanner.Name)
//line pkg/report/templates/default.qtpl:103
		qw422016.N().S(`</p>
                                    <p class="my-0">Vendor:  `)
//line pkg/report/templates/default.qtpl:104
		qw422016.E().S(p.VulnsReports[0].Report.Scanner.Vendor)
//line pkg/report/templates/default.qtpl:104
		qw422016.N().S(`</p>
                                    <p class="my-0">Version:  `)
//line pkg/report/templates/default.qtpl:105
		qw422016.E().S(p.VulnsReports[0].Report.Scanner.Version)
//line pkg/report/templates/default.qtpl:105
		qw422016.N().S(`</p>
                                </div>
                             </div>
                        </div>
                        <!-- summary -->
                        <div class="col-3 border rounded shadow px-3 py-2 mx-auto ">
                            <div class="row text-center">
                               <div class="col">
                                   <p class="mb-2 pb-1 border-bottom">Summary</p>
                               </div>
                            </div>
                            <div class="row">
                                `)
//line pkg/report/templates/default.qtpl:118
		summary := p.GetMergedVulnsSummary()

//line pkg/report/templates/default.qtpl:119
		qw422016.N().S(`
                                <div class="col-6">
                                    <p class="my-0">CRITICAL  `)
//line pkg/report/templates/default.qtpl:121
		qw422016.N().D(summary.CriticalCount)
//line pkg/report/templates/default.qtpl:121
		qw422016.N().S(`</p>
                                    <p class="my-0">HIGH  `)
//line pkg/report/templates/default.qtpl:122
		qw422016.N().D(summary.HighCount)
//line pkg/report/templates/default.qtpl:122
		qw422016.N().S(`</p>
                                    <p class="my-0">MEDIUM  `)
//line pkg/report/templates/default.qtpl:123
		qw422016.N().D(summary.MediumCount)
//line pkg/report/templates/default.qtpl:123
		qw422016.N().S(`</p>        
                                </div>
                                <div class="col-6">
                                    <p class="my-0">LOW  `)
//line pkg/report/templates/default.qtpl:126
		qw422016.N().D(summary.LowCount)
//line pkg/report/templates/default.qtpl:126
		qw422016.N().S(`</p>
                                    <p class="my-0">UNKNOWN  `)
//line pkg/report/templates/default.qtpl:127
		qw422016.N().D(summary.UnknownCount)
//line pkg/report/templates/default.qtpl:127
		qw422016.N().S(`</p>
                                </div>
                            </div>
                        </div>
                        <!-- Metadata -->
                        <div class="col-3 border rounded shadow px-3 py-2 mr-4">
                            <div class="row text-center">
                                <div class="col">
                                    <p class="mb-2 pb-1 border-bottom">Metadata</p>
                                </div>
                             </div>
                             <div class="row">
                                <div class="col">
                                    <p class="my-0">Generated at:  `)
//line pkg/report/templates/default.qtpl:140
		qw422016.E().S(p.VulnsReports[0].CreationTimestamp.String())
//line pkg/report/templates/default.qtpl:140
		qw422016.N().S(`</p>
                                </div>
                             </div>
                        </div>

                    </div>      
                </div>
                `)
//line pkg/report/templates/default.qtpl:147
	}
//line pkg/report/templates/default.qtpl:147
	qw422016.N().S(`
                
                `)
//line pkg/report/templates/default.qtpl:149
	for count, report := range p.VulnsReports {
//line pkg/report/templates/default.qtpl:149
		qw422016.N().S(`
                
                  <div class="row"><h5 class="text-info" id="vulns_container_`)
//line pkg/report/templates/default.qtpl:151
		qw422016.N().D(count)
//line pkg/report/templates/default.qtpl:151
		qw422016.N().S(`">Container `)
//line pkg/report/templates/default.qtpl:151
		qw422016.E().S(report.Labels["starboard.container.name"])
//line pkg/report/templates/default.qtpl:151
		qw422016.N().S(`</h5></div>
                  <div class="row"><p>`)
//line pkg/report/templates/default.qtpl:152
		qw422016.E().S(report.Report.Registry.URL)
//line pkg/report/templates/default.qtpl:152
		qw422016.N().S(`/`)
//line pkg/report/templates/default.qtpl:152
		qw422016.E().S(report.Report.Artifact.Repository)
//line pkg/report/templates/default.qtpl:152
		qw422016.N().S(`:`)
//line pkg/report/templates/default.qtpl:152
		qw422016.E().S(report.Report.Artifact.Tag)
//line pkg/report/templates/default.qtpl:152
		qw422016.N().S(`</p></div>
                  `)
//line pkg/report/templates/default.qtpl:153
		if len(report.Report.Vulnerabilities) == 0 {
//line pkg/report/templates/default.qtpl:153
			qw422016.N().S(`
                    <div class="row">
                      <p class="alert alert-success py-0 m-0" style="font-size: small;">No Vulnerabilities</p>
                    </div>                  
                  `)
//line pkg/report/templates/default.qtpl:157
		} else {
//line pkg/report/templates/default.qtpl:157
			qw422016.N().S(`

                  <div class="row">
                      <table class="table table-sm table-bordered">
                          <thead>
                              <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Severity</th>
                                <th scope="col">Resource</th>
                                <th scope="col">Installed Version</th>
                                <th scope="col">Fixed Version</th>
                              </tr>
                            </thead>
                            <tbody>
                  `)
//line pkg/report/templates/default.qtpl:171
			for _, v := range report.Report.Vulnerabilities {
//line pkg/report/templates/default.qtpl:171
				qw422016.N().S(`
                    <tr>
                      <td>`)
//line pkg/report/templates/default.qtpl:173
				qw422016.E().S(v.VulnerabilityID)
//line pkg/report/templates/default.qtpl:173
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:174
				qw422016.E().S(string(v.Severity))
//line pkg/report/templates/default.qtpl:174
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:175
				qw422016.E().S(v.Resource)
//line pkg/report/templates/default.qtpl:175
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:176
				qw422016.E().S(v.InstalledVersion)
//line pkg/report/templates/default.qtpl:176
				qw422016.N().S(`</td>
                      <td>`)
//line pkg/report/templates/default.qtpl:177
				qw422016.E().S(v.FixedVersion)
//line pkg/report/templates/default.qtpl:177
				qw422016.N().S(`</td>
                    </tr>	
                  `)
//line pkg/report/templates/default.qtpl:179
			}
//line pkg/report/templates/default.qtpl:179
			qw422016.N().S(`
                            </tbody>
                      </table>
                  </div>
                `)
//line pkg/report/templates/default.qtpl:183
		}
//line pkg/report/templates/default.qtpl:183
		qw422016.N().S(`
                `)
//line pkg/report/templates/default.qtpl:184
	}
//line pkg/report/templates/default.qtpl:184
	qw422016.N().S(`
                

                <!-- Config Audits -->
                `)
//line pkg/report/templates/default.qtpl:188
	if len(p.ConfigAuditReports) > 0 {
//line pkg/report/templates/default.qtpl:188
		qw422016.N().S(`
                  <div class="row pt-3 text-center border-bottom my-4">
                      <h3 class="mx-auto" id="ca_header" style="color: rgb(0, 160, 170);">Configuration Audit</h3>
                  </div>
                `)
//line pkg/report/templates/default.qtpl:192
	}
//line pkg/report/templates/default.qtpl:192
	qw422016.N().S(`
                `)
//line pkg/report/templates/default.qtpl:193
	for _, report := range p.ConfigAuditReports {
//line pkg/report/templates/default.qtpl:193
		qw422016.N().S(`        
                  <div class="row"><h5 class="text-info" id="ca_pod_checks">Pod Checks</h5></div>
                  <div class="row">
                      <table class="table table-sm table-bordered">
                          <thead>
                              <tr>
                                <th scope="col">Success</th>
                                <th scope="col">ID</th>
                                <th scope="col">Severity</th>
                                <th scope="col">Category</th>
                              </tr>
                            </thead>
                            <tbody>
                              `)
//line pkg/report/templates/default.qtpl:206
		for _, check := range report.Report.PodChecks {
//line pkg/report/templates/default.qtpl:206
			qw422016.N().S(`
                                <tr>
                                  <td>`)
//line pkg/report/templates/default.qtpl:208
			qw422016.E().V(check.Success)
//line pkg/report/templates/default.qtpl:208
			qw422016.N().S(`</td>
                                  <td>`)
//line pkg/report/templates/default.qtpl:209
			qw422016.E().S(check.ID)
//line pkg/report/templates/default.qtpl:209
			qw422016.N().S(`</td>
                                  <td>`)
//line pkg/report/templates/default.qtpl:210
			qw422016.E().S(check.Severity)
//line pkg/report/templates/default.qtpl:210
			qw422016.N().S(`</td>
                                  <td>`)
//line pkg/report/templates/default.qtpl:211
			qw422016.E().S(check.Category)
//line pkg/report/templates/default.qtpl:211
			qw422016.N().S(`</td>
                                </tr>
                              `)
//line pkg/report/templates/default.qtpl:213
		}
//line pkg/report/templates/default.qtpl:213
		qw422016.N().S(`
                            </tbody>
                      </table>
                  </div>
                  `)
//line pkg/report/templates/default.qtpl:217
		for container, checks := range report.Report.ContainerChecks {
//line pkg/report/templates/default.qtpl:217
			qw422016.N().S(`
                    <div class="row"><h5 class="text-info" id="ca_container_`)
//line pkg/report/templates/default.qtpl:218
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:218
			qw422016.N().S(`">Container `)
//line pkg/report/templates/default.qtpl:218
			qw422016.E().S(container)
//line pkg/report/templates/default.qtpl:218
			qw422016.N().S(`</h5></div>
                    <div class="row">
                        <table class="table table-sm table-bordered">
                            <thead>
                                <tr>
                                  <th scope="col">Success</th>
                                  <th scope="col">ID</th>
                                  <th scope="col">Severity</th>
                                  <th scope="col">Category</th>
                                </tr>
                              </thead>
                              <tbody>
                                `)
//line pkg/report/templates/default.qtpl:230
			for _, check := range checks {
//line pkg/report/templates/default.qtpl:230
				qw422016.N().S(`
                                  <tr>
                                    <td>`)
//line pkg/report/templates/default.qtpl:232
				qw422016.E().V(check.Success)
//line pkg/report/templates/default.qtpl:232
				qw422016.N().S(`</td>
                                    <td>`)
//line pkg/report/templates/default.qtpl:233
				qw422016.E().S(check.ID)
//line pkg/report/templates/default.qtpl:233
				qw422016.N().S(`</td>
                                    <td>`)
//line pkg/report/templates/default.qtpl:234
				qw422016.E().S(check.Severity)
//line pkg/report/templates/default.qtpl:234
				qw422016.N().S(`</td>
                                    <td>`)
//line pkg/report/templates/default.qtpl:235
				qw422016.E().S(check.Category)
//line pkg/report/templates/default.qtpl:235
				qw422016.N().S(`</td>
                                  </tr>
                                `)
//line pkg/report/templates/default.qtpl:237
			}
//line pkg/report/templates/default.qtpl:237
			qw422016.N().S(`
                              </tbody>
                        </table>
                    </div>
                  `)
//line pkg/report/templates/default.qtpl:241
		}
//line pkg/report/templates/default.qtpl:241
		qw422016.N().S(`
                `)
//line pkg/report/templates/default.qtpl:242
	}
//line pkg/report/templates/default.qtpl:242
	qw422016.N().S(`
            </div>
        </div>
`)
//line pkg/report/templates/default.qtpl:245
}

//line pkg/report/templates/default.qtpl:245
func (p *ReportPage) WriteBody(qq422016 qtio422016.Writer) {
//line pkg/report/templates/default.qtpl:245
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/default.qtpl:245
	p.StreamBody(qw422016)
//line pkg/report/templates/default.qtpl:245
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/default.qtpl:245
}

//line pkg/report/templates/default.qtpl:245
func (p *ReportPage) Body() string {
//line pkg/report/templates/default.qtpl:245
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/default.qtpl:245
	p.WriteBody(qb422016)
//line pkg/report/templates/default.qtpl:245
	qs422016 := string(qb422016.B)
//line pkg/report/templates/default.qtpl:245
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/default.qtpl:245
	return qs422016
//line pkg/report/templates/default.qtpl:245
}
