// Code generated by qtc from "node_report.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/report/templates/node_report.qtpl:1
package templates

//line pkg/report/templates/node_report.qtpl:1
import "github.com/aquasecurity/starboard/pkg/apis/aquasecurity/v1alpha1"

//line pkg/report/templates/node_report.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/report/templates/node_report.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/report/templates/node_report.qtpl:3
func (p *NodeReport) StreamTitle(qw422016 *qt422016.Writer) {
//line pkg/report/templates/node_report.qtpl:3
	qw422016.N().S(`
Aqua Starboard Node Security Report - Node: `)
//line pkg/report/templates/node_report.qtpl:4
	qw422016.E().S(p.Node.Name)
//line pkg/report/templates/node_report.qtpl:4
	qw422016.N().S(`
`)
//line pkg/report/templates/node_report.qtpl:5
}

//line pkg/report/templates/node_report.qtpl:5
func (p *NodeReport) WriteTitle(qq422016 qtio422016.Writer) {
//line pkg/report/templates/node_report.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/node_report.qtpl:5
	p.StreamTitle(qw422016)
//line pkg/report/templates/node_report.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/node_report.qtpl:5
}

//line pkg/report/templates/node_report.qtpl:5
func (p *NodeReport) Title() string {
//line pkg/report/templates/node_report.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/node_report.qtpl:5
	p.WriteTitle(qb422016)
//line pkg/report/templates/node_report.qtpl:5
	qs422016 := string(qb422016.B)
//line pkg/report/templates/node_report.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/node_report.qtpl:5
	return qs422016
//line pkg/report/templates/node_report.qtpl:5
}

//line pkg/report/templates/node_report.qtpl:7
func (p *NodeReport) StreamBody(qw422016 *qt422016.Writer) {
//line pkg/report/templates/node_report.qtpl:7
	qw422016.N().S(`
<div class="container">

  <div class="col mt-5">
    <div class="row text-center">`)
//line pkg/report/templates/node_report.qtpl:11
	streamimgAquaLogo(qw422016)
//line pkg/report/templates/node_report.qtpl:11
	qw422016.N().S(`</div>
    <div class="row mt-4 text-center">
      <h2 class="text-muted mx-auto">Aqua Starboard Node Security Report</h2>
    </div>
    <div class="row text-center">
      <h3 class="text-muted mx-auto">`)
//line pkg/report/templates/node_report.qtpl:16
	qw422016.E().S(string(p.Node.Kind))
//line pkg/report/templates/node_report.qtpl:16
	qw422016.N().S(`: `)
//line pkg/report/templates/node_report.qtpl:16
	qw422016.E().S(p.Node.Name)
//line pkg/report/templates/node_report.qtpl:16
	qw422016.N().S(`</h3>
    </div>
    <div class="row text-center">
      <h3 class="text-muted mx-auto">Generated on `)
//line pkg/report/templates/node_report.qtpl:19
	qw422016.E().S(p.GeneratedAt.Format("2 Jan 2006 15:04:01"))
//line pkg/report/templates/node_report.qtpl:19
	qw422016.N().S(`</h3>
    </div>
  </div>

  <h3>Vulnerabilities by Node</h3>
  <div class="row">
    <table class="table table-sm table-bordered">
      <thead>
        <tr>
          <th scope="col">Node</th>
          <th scope="col">Critical</th>
          <th scope="col">High</th>
          <th scope="col">Other</th>
        </tr>
      </thead>
      <tbody>
      `)
//line pkg/report/templates/node_report.qtpl:35
	for _, report := range p.Vulnerabilities {
//line pkg/report/templates/node_report.qtpl:35
		qw422016.N().S(`
      `)
//line pkg/report/templates/node_report.qtpl:37
		summary := report.Report.Summary
		otherCount := summary.PassCount + summary.InfoCount + summary.WarnCount

//line pkg/report/templates/node_report.qtpl:39
		qw422016.N().S(`
      <tr>
        <td>`)
//line pkg/report/templates/node_report.qtpl:41
		streamnodeReference(qw422016, report.Report.Sections)
//line pkg/report/templates/node_report.qtpl:41
		qw422016.N().S(`</td>
        <td>`)
//line pkg/report/templates/node_report.qtpl:42
		qw422016.N().D(summary.PassCount)
//line pkg/report/templates/node_report.qtpl:42
		qw422016.N().S(`</td>
        <td>`)
//line pkg/report/templates/node_report.qtpl:43
		qw422016.N().D(summary.InfoCount)
//line pkg/report/templates/node_report.qtpl:43
		qw422016.N().S(`</td>
        <td>`)
//line pkg/report/templates/node_report.qtpl:44
		qw422016.N().D(otherCount)
//line pkg/report/templates/node_report.qtpl:44
		qw422016.N().S(`</td>
      </tr>
      `)
//line pkg/report/templates/node_report.qtpl:46
	}
//line pkg/report/templates/node_report.qtpl:46
	qw422016.N().S(`
      </tbody>
    </table>
  </div>

</div>
`)
//line pkg/report/templates/node_report.qtpl:52
}

//line pkg/report/templates/node_report.qtpl:52
func (p *NodeReport) WriteBody(qq422016 qtio422016.Writer) {
//line pkg/report/templates/node_report.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/node_report.qtpl:52
	p.StreamBody(qw422016)
//line pkg/report/templates/node_report.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/node_report.qtpl:52
}

//line pkg/report/templates/node_report.qtpl:52
func (p *NodeReport) Body() string {
//line pkg/report/templates/node_report.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/node_report.qtpl:52
	p.WriteBody(qb422016)
//line pkg/report/templates/node_report.qtpl:52
	qs422016 := string(qb422016.B)
//line pkg/report/templates/node_report.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/node_report.qtpl:52
	return qs422016
//line pkg/report/templates/node_report.qtpl:52
}

//line pkg/report/templates/node_report.qtpl:54
func streamnodeReference(qw422016 *qt422016.Writer, section []v1alpha1.CISKubeBenchSection) {
//line pkg/report/templates/node_report.qtpl:54
	qw422016.N().S(`
  `)
//line pkg/report/templates/node_report.qtpl:55
	qw422016.E().S(section[0].ID)
//line pkg/report/templates/node_report.qtpl:55
	qw422016.N().S(`/`)
//line pkg/report/templates/node_report.qtpl:55
	qw422016.E().S(section[0].Text)
//line pkg/report/templates/node_report.qtpl:55
	qw422016.N().S(`:`)
//line pkg/report/templates/node_report.qtpl:55
	qw422016.E().S(section[0].NodeType)
//line pkg/report/templates/node_report.qtpl:55
	qw422016.N().S(`
`)
//line pkg/report/templates/node_report.qtpl:56
}

//line pkg/report/templates/node_report.qtpl:56
func writenodeReference(qq422016 qtio422016.Writer, section []v1alpha1.CISKubeBenchSection) {
//line pkg/report/templates/node_report.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/report/templates/node_report.qtpl:56
	streamnodeReference(qw422016, section)
//line pkg/report/templates/node_report.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line pkg/report/templates/node_report.qtpl:56
}

//line pkg/report/templates/node_report.qtpl:56
func nodeReference(section []v1alpha1.CISKubeBenchSection) string {
//line pkg/report/templates/node_report.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/report/templates/node_report.qtpl:56
	writenodeReference(qb422016, section)
//line pkg/report/templates/node_report.qtpl:56
	qs422016 := string(qb422016.B)
//line pkg/report/templates/node_report.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/report/templates/node_report.qtpl:56
	return qs422016
//line pkg/report/templates/node_report.qtpl:56
}
